version: "3.8"

services: 
   backend:
      build: ./Myntra-Backend
      ports:
        - "8080:8080"
      volumes:
        - ./Myntra-Backend:/usr/src/app
      command: [ "node", "server.js" ]
   frontend:
      build: .
      ports:
        - "3000:3000"
      environment:
        - NODE_OPTIONS=--openssl-legacy-provider
      volumes:
        - ./:/usr/src/app
      depends_on:
        - backend
      command: [ "npm", "start" ]